set :application_name, 'meeanw-telegram-bot'
set :deploy_to, '/var/www/meeanw-telegram-bot'
set :domain, '52.3.65.144'
set :identity_file, '~/.ssh/personal/id_rsa_meandyou.space_aws_ec2'
set :user, 'deployer'
set :repository, 'git@github.com-kokorolx:sudox-global/meeanw-telegram-bot.git'
set :branch, 'master'